apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aline-EKS-cluster-MM
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-072c681478c27ecef } # Parameterize
      us-east-1b: { id: subnet-04d2520494555786c }

managedNodeGroups:
  - name: eks-cluster
    minSize: 4
    maxSize: 5
    desiredCapacity: 4
    instanceType: t2.micro # Parameterize
    ssh:
      publicKeyName: aline-keys
    labels: { role: worker }
    privateNetworking: true