apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deployment
  labels:
    app: bank-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-microservice
  template:
    metadata:
      labels:
        app: bank-microservice
    spec:
      containers:
        - name: bank-microservice
          image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mm-bank-microservice:latest
          resources:
            requests:
              memory: 64Mi
              cpu: 250m # 0.25 CPU
            limits:
              memory: 512Mi
              cpu: 500m
          ports:
            - name: bank-port
              containerPort: 8002
          env:
          - name: APP_PORT
            value: "8002"
          envFrom:
          - secretRef:
              name: microservice-secret
          - configMapRef:
              name: microservice-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
spec:
  type: NodePort
  selector:
    app: bank-microservice
  ports:
    - protocol: TCP
      port: 8002
      targetPort: bank-port