apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: microservices-microservice
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30001
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30002
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30003
    - protocol: TCP
      port: 8004
      targetPort: 8004
      nodePort: 30004