apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
  labels:
    app: transaction-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-microservice
  template:
    metadata:
      labels:
        app: transaction-microservice
    spec:
      containers:
        - name: transaction-microservice
          image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mm-transaction-microservice:latest
          resources:
            requests:
              memory: 64Mi
              cpu: 250m # 0.25 CPU
            limits:
              memory: 512Mi # Exactly half of 1 GiB
              cpu: 500m # 0.5 CPU
          ports:
            - name: ta-port
              containerPort: 8004
          env:
          - name: APP_PORT
            value: "8004"
          envFrom:
          - secretRef:
              name: microservice-secret
          - configMapRef:
              name: microservice-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  type: NodePort
  selector:
    app: transaction-microservice
  ports:
    - protocol: TCP
      port: 8004
      targetPort: ta-port