apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      containers:
        - name: user-microservice
          image: ${AWS_ACC_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mm-bank-microservice:latest
          resources:
            requests:
              memory: 64Mi
              cpu: 250m # 0.25 CPU
            limits:
              memory: 512Mi # Exactly half of 1 GiB; load testing to get efficient limits
              cpu: 500m # 0.5 CPU
          ports:
            - name: user-port
              containerPort: 8003
          env:
          - name: APP_PORT
            value: "8003"
          envFrom:
          - secretRef:
              name: microservice-secret
          - configMapRef:
              name: microservice-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: LoadBalancer
  selector:
    app: user-microservice
  ports:
    - protocol: TCP
      port: 8003
      targetPort: user-port
      nodePort: 30003